app/urls.py
from django.contrib import admin

from django.urls import path, include


urlpatterns = [

    path('', include(('bases.urls', 'bases'), namespace='bases')),
    path('inv/', include(('inv.urls', 'inv'), namespace='inv')),

    path('admin/', admin.site.urls),

]

inv/urls.py
from django.urls import path

from .views import Categoriaview, CategoriaNew, CategoriaEdit,  \
      CategoriaDel, \
      SubcategoriaView, SubCategoriaNew, SubCategoriaEdit, SubCategoriaDel, \
       MarcaView, MarcaNew, MarcaEdit, marca_inactivar, \
        UMView, UMNew, UMEdit, um_inactivar,\
    ProductoView, ProductoEdit, ProductoNew, producto_inactivar

urlpatterns = [
    path('categorias/', Categoriaview.as_view(), name='categoria_list'),
    path('categorias/new', CategoriaNew.as_view(), name='categoria_new'),
    path('categorias/edit/<int:pk>',CategoriaEdit.as_view(), name='categoria_edit'),
    path('categorias/delete/<int:pk>',CategoriaDel.as_view(), name='categoria_edit'),

    path('subcategorias/',SubcategoriaView.as_view(), name='subcategoria_list'),
    path('subcategorias/new',SubCategoriaNew.as_view(), name='subcategoria_list'),
    path('subcategorias/edit/<int:pk>',SubCategoriaEdit.as_view(), name='subcategoria_edit'),
    path('subcategorias/delete/<int:pk>',SubCategoriaDel.as_view(), name='subcategoria_edit'),
    
     path('marcas/',MarcaView.as_view(), name="marca_list"),
    path('marcas/new',MarcaNew.as_view(), name="marca_new"),
    path('marcas/edit/<int:pk>',MarcaEdit.as_view(), name="marca_edit"),
    path('marcas/inactivar/<int:id>',marca_inactivar, name="marca_inactivar"),

     path('um/',UMView.as_view(), name="um_list"),
    path('um/new',UMNew.as_view(), name="um_new"),
    path('um/edit/<int:pk>',UMEdit.as_view(), name="um_edit"),
    path('um/inactivar/<int:id>',um_inactivar, name="um_inactivar"),

    path('productos/',ProductoView.as_view(), name="producto_list"),
    path('productos/new',ProductoNew.as_view(), name="producto_new"),
    path('productos/edit/<int:pk>',ProductoEdit.as_view(), name="producto_edit"),
    path('productos/inactivar/<int:id>',producto_inactivar, name="producto_inactivar"),

]

bases/models.py
from django.db import models
from django.contrib.auth.models import User

class ClaseModelo(models.Model):

    estado = models.BooleanField(default=True) #modelo de la base

    fc = models.DateField(auto_now_add=True) #fecha de creacion cuando el registro se cree
   
    fn = models.DateTimeField(auto_now=True)  #fecha de modificado

    uc = models.ForeignKey(User, on_delete=models.CASCADE) #un usuario en mucho

    um = models.IntegerField(blank=True, null=True)
    
    
    class Meta: #modelo de tipo abstracto para notificar a django que no tome el modelo en cuenta
        abstract = True

inv/models.py
from django.db import models

from bases.models import ClaseModelo

class Categoria(ClaseModelo): #hereda de moder.url
    descripcion = models.CharField(
        max_length=100,
        help_text='Descripcion de la Caterogira',
        unique=True
    )

    def _str_(self):
        return '()'.format(self.descripcion)
    
    def save(self):
        self.descripcion = self.descripcion.Upper() #Guarda los datos y los deja en mayuscula en el servidor.
        super(Categoria, self).save()

    class Meta:
        verbose_name_plural= "Categorias"  #Guarda en la clase Categorias.

class Subcategoria(ClaseModelo):
    Categoria=models.Foreignkey(Categoria, on_delete=models.CASCADE)
    descripcion = models.CharField(
        max_length=100,
        help_text='Descripcion de la Categoria',

    )

    def __str__(self):
        return '{}:{}'.format(self.categoriadescripcion,self.descripcion)
    
    def save(self):
        self.descripcion = self.descripcion.upper()
        super(Subcategoria, self).save()
    
    class Meta:
        verbose_name_plural="Sub Categorias"
        unique_together =('categoria','descripcion')

class Marca(ClaseModelo):
    descripcion = models.CharField(
        max_length=100,
        help_text='Descripción de la Marca',
        unique=True
    )

    def __str__(self):
        return '{}'.format(self.descripcion)

    def save(self):
        self.descripcion = self.descripcion.upper()
        super(Marca, self).save()

    class Meta:
        verbose_name_plural = "Marca"


class UnidadMedida(ClaseModelo):
    descripcion = models.CharField(
        max_length=100,
        help_text='Descripción de la Unidad Medida',
        unique=True
    )

    def __str__(self):
        return '{}'.format(self.descripcion)

    def save(self):
        self.descripcion = self.descripcion.upper()
        super(UnidadMedida, self).save()

    class Meta:
        verbose_name_plural = "Unidades de Medida"


class Producto(ClaseModelo):
    codigo = models.CharField(
        max_length=20,
        unique=True
    )
    codigo_barra = models.CharField(max_length=50)
    descripcion = models.CharField(max_length=200)
    precio = models.FloatField(default=0)
    existencia = models.IntegerField(default=0)
    ultima_compra = models.DateField(null=True, blank=True)

    marca = models.ForeignKey(Marca, on_delete=models.CASCADE)
    unidad_medida = models.ForeignKey(UnidadMedida, on_delete=models.CASCADE)
    subcategoria = models.ForeignKey(Subcategoria, on_delete=models.CASCADE)
    foto = models.ImageField(upload_to="images/",null=True,blank=True)

    def __str__(self):
        return '{}'.format(self.descripcion)
    
    def save(self):
        self.descripcion = self.descripcion.upper()
        super(Producto,self).save()
    
    class Meta:
        verbose_name_plural = "Productos"
        unique_together = ('codigo','codigo_barra')

inv/forms.py
from typing import Any, Mapping
from django import forms
from django.core.files.base import File
from django.db.models.base import Model
from django.forms.utils import ErrorList

from .models import Categoria, Subcategoria, Marca,\
     UnidadMedida, Producto


class CategoriaForm(forms.ModelForm):
    class Meta:
        model=Categoria
        fields = ['descripcion','estado']
        labels = {'descripcion': "Descripción de la Categoria",
                  "estado":"Estado"}
        widget={'descripcion': forms.TextInput}

    def __init__(self, *args, **kwargs):
        super().__init__(*args,**kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class':'form-control'
            })

class SubCategoriaForm(forms.ModelForm):
    categoria = forms.ModelChoiceField(
        queryset=Categoria.dbjets.filter(estado=True)
        .order_by('descripcion')
    )
    class Meta:
        model=Subcategoria
        fields = ['categoria','descripcion','estado']
        labels = {'descripcion': "SubCategoria",
                  "estado":"Estado"}
        widget={'descripcion': forms.TextInput}

    def __init__(self, *args, **kwargs):
        super().__init__(*args,**kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class':'form-control'
            })
        self.fields['categoria'].empty_label ="Seleccione Categoria"

class MarcaForm(forms.ModelForm):
    class Meta:
        model=Marca
        fields = ['descripcion','estado']
        labels= {'descripcion': "Descripción de la Marca",
                "estado":"Estado"}
        widget={'descripcion': forms.TextInput()}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })


class UMForm(forms.ModelForm):
    class Meta:
        model=UnidadMedida
        fields = ['descripcion','estado']
        labels= {'descripcion': "Descripción de la Marca",
                "estado":"Estado"}
        widget={'descripcion': forms.TextInput()}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })


class ProductoForm(forms.ModelForm):
    class Meta:
        model=Producto
        fields=['codigo','codigo_barra','descripcion','estado', \
                'precio','existencia','ultima_compra',
                'marca','subcategoria','unidad_medida','foto']
        exclude = ['um','fm','uc','fc']
        widget={'descripcion': forms.TextInput()}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })
        self.fields['ultima_compra'].widget.attrs['readonly'] = True
        self.fields['existencia'].widget.attrs['readonly'] = True

inv/views.py
from django.shortcuts import render, redirect
from django.views import generic
from django.urls import reverse_lazy

from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Categoria,Subcategoria
from .forms import CategoriaForm, SubCategoriaForm
# Create your views here.

class Categoriaview(LoginRequiredMixin, generic.ListView):
    model = Categoria
    template = "inv/categoria_list.html"
    context_object_name = "obj"
    login_url = 'bases:login'

class CategoriaNew(LoginRequiredMixin, generic.CreateView):
    model=Categoria
    template_name="inv/categoria_form.html"
    context_objet_name = "obj"
    form_class=CategoriaForm
    success_url=reverse_lazy("inv:categoria_list")
    login_url="bases:login"

    def form_valid(self, form):
        form.instance.uc = self.request.user
        return super().form_valid(form)

class CategoriaEdit(LoginRequiredMixin, generic.UpdateView):
    model=Categoria
    template_name="inv/categoria_form.html"
    context_objet_name = "obj"
    form_class=CategoriaForm
    success_url=reverse_lazy("inv:categoria_list")
    login_url="bases:login"

    def form_valid(self, form):
        form.instance.um = self.request.user.id
        return super().form_valid(form)

class CategoriaDel(LoginRequiredMixin, generic.DeleteView):
    model=Categoria
    template_name='inv/catalogos_del.html'
    context_object_name='obj'
    success_url=reverse_lazy("inv:categoria_list")

class SubCategoria(LoginRequiredMixin, generic.ListView):
    model = Subcategoria
    template = "inv/subcategoria_list.html"
    context_object_name = "obj"
    login_url = 'bases:login'

class SubCategoriaNew(LoginRequiredMixin, generic.CreateView):  # Alineada correctamente
    model = Subcategoria
    template_name = "inv/subcategoria_form.html"
    context_object_name = "obj"
    form_class = SubCategoriaForm
    success_url = reverse_lazy("inv:subcategoria_list")
    login_url = "bases:login"

    def form_valid(self, form):
        form.instance.uc = self.request.user
        return super().form_valid(form)

class SubCategoriaEdit(LoginRequiredMixin, generic.UpdateView):
    model=SubCategoria
    template_name="inv/subcategoria_form.html"
    context_objet_name = "obj"
    form_class=SubCategoriaForm
    success_url=reverse_lazy("inv:subcategoria_list")
    login_url="bases:login"

    def form_valid(self, form):
        form.instance.um = self.request.user.id
        return super().form_valid(form)

class SubCategoriaDel(LoginRequiredMixin, generic.DeleteView):
    model=SubCategoria
    template_name='inv/catalogos_del.html'
    context_object_name='obj'
    success_url=reverse_lazy("inv:subcategoria_list")


def marca_inactivar(request,id ):
    marca = marca.objects.filter(pk=id).first()
    contexto={}
    template_name="inv/catalogo_del.thml"

    if not marca:
        return redirect("inv:marca_list")
    
    if request.method=="GET":
        contexto={'obj': marca}
    
    if request.metchod=='POST':
        marca.estado=False
        marca.save()
        return redirect("inv:marca_list")

    return render(request,template_name,contexto)

inv/templates/inv/categoria_list.html
{% extends 'base/base.html' %}
{% block page_content %}

<div class="card mb-4">
    <div class="card-header">
        Default Card Example
    </div>
    <div class="card-body">
        This card uses Bootstrap's default styling with no utility classes added. Global
        styles are the only things modifying the look and feel of this default card example.
    </div>
</div>

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Basic Card Example</h6>
    </div>
    <div class="card-body">
        The styling for this basic card example is created by using default Bootstrap
        utility classes. By using utility classes, the style of the card component can be
        easily modified with no need for any custom CSS!
    </div>
</div>

{% endblock %}

{%  block js_page %}
{% endblock %}

inv/templates/inv/marca_list.html
{% extends 'base/base.html' %}

{% block page_content %}
<div class="card shadow mb-4">
  <!-- Card Header - Dropdown -->
  <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
    <h6 class="m-0 font-weight-bold text-primary">Listado de Unidad de Marca</h6>
    <div class="dropdown no-arrow">
      <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
      </a>
      <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
        <div class="dropdown-header">Acciones:</div>
        <a class="dropdown-item" href="{% url 'inv:marca_new' %}"><i class="far fa-calendar-plus"></i> Nueva</a>
      </div>
    </div>
  </div>
  <!-- Card Body -->
  <div class="card-body">
    {% if not obj %}
    <div class="alert alert-info">No hay Marca</div>
    {% endif %}
    <table class="table table-striped table-hover">
      <thead>
        <th>Id</th>
        <th>Descripción</th>
        <th>Estado</th>
        <th>F. Creado</th>
        <th>F. Modif</th>
        <th class="all">Acciones</th>
      </thead>
      <tbody>
        {% for item in obj%}
        <tr>
          <td>{{ item.id }}</td>
          <td>{{ item.descripcion }}</td>
          <td>{{item.estado|yesno:"Activo,Inactivo"}}</td>
          <td>{{ item.fc|date:"d/m/Y H:i:s" }}</td>
          <td>{{ item.fm|date:"d/m/Y H:i:s"}}</td>
          <td>
            <a href="{% url 'inv:marca_edit' item.id %}" class="btn btn-warning btn-circle" role="button"><i class="far fa-edit"></i></a> 
            <a href="{% url 'inv:marca_inactivar' item.id %}" class="btn btn-danger btn-circle" role="button"><i class="far fa-thumbs-down"></i></a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock %}
{% block js_page %}
<script>
// Call the dataTables jQuery plugin
$(document).ready(function() {
  $('.table').DataTable();
});
</script>
{% endblock %}

inv/templates/inv/producto_form.html
<div class="modal-dialog modal-lg">
    <div class="modal-content">
        {% if obj %}
        <form method="POST" role="form" class="form-inline" action="{% url 'inv:producto_edit' obj.pk %}" enctype="multipart/form-data" >
        {% else %}
        <form method="POST" role="form" class="form-inline" action="{% url 'inv:producto_new' %}"  enctype="multipart/form-data" >
        {% endif %}
            <div class="col-xl-12 col-md-12 mb-12">
                {% if obj %}
                <div class="card border-left-warning shadow h-100 py-2">
                {% else %}
                <div class="card border-left-success shadow h-100 py-2">
                {% endif %}
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                            {% if obj %} Editar {% else %} Nueva {% endif %} Producto
                        </div>
                        <div class="dropdown-divider"></div>
                        {% csrf_token %}
                        <div class="row">
                            {#{ form.as_p }#}
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="col-md-6">{{form.codigo.label}}</div>
                                <div class="col-md-6">{{form.codigo}}</div>
                            </div>

                            <div class="col-md-6">
                                <div class="col-md-6">{{form.codigo_barra.label}}</div>
                                <div class="col-md-6">{{form.codigo_barra}}</div>    
                            </div>                            
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="col-md-6">{{form.descripcion.label}}</div>
                                <div class="col-md-6">{{form.descripcion}}</div>
                            </div>

                            <div class="col-md-6">
                                <div class="col-md-6">{{form.estado.label}}</div>
                                <div class="col-md-6">{{form.estado}}</div>    
                            </div>                            
                        </div>
                        
                        <div class="row">
                            <div class="col-md-6">
                                <div class="col-md-6">{{form.precio.label}}</div>
                                <div class="col-md-6">{{form.precio}}</div>
                            </div>

                            <div class="col-md-6">
                                <div class="col-md-6">{{form.existencia.label}}</div>
                                <div class="col-md-6">{{form.existencia}}</div>    
                            </div>                            
                        </div>

                        <div class="row">
                            <div class="col-md-4">
                                <div class="col-md-6">{{form.ultima_compra.label}}</div>
                                <div class="col-md-6">{{form.ultima_compra}}</div>
                            </div>

                            <div class="col-md-4">
                                <div class="col-md-6">{{form.marca.label}}</div>
                                <div class="col-md-6">{{form.marca}}</div>    
                            </div>     
                            <div class="col-md-4">
                                <div class="col-md-6">{{form.unidad_medida.label}}</div>
                                <div class="col-md-6">{{form.unidad_medida}}</div>    
                            </div>                        
                        </div>

                        <div class="row">
                            <div class="col-md-6">
                                <div class="col-md-6">Categoría</div>
                                <div class="col-md-6">
                                    <select name="categoria" id="id_categoria" class="form-control from-control-sm">
                                        <option value="0">-------</option>
                                        {% for item in categorias %}
                                        <option value="{{item.id}}">{{item.descripcion}}</option>
                                        {% endfor%}
                                    </select>
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="col-md-6">Sub Categoría</div>
                                <div class="col-md-6">
                                    <select name="subcategoria" id="id_subcategoria" class="form-control from-control-sm">
                                        <option value="0">-------</option>
                                        {% for item in subcategorias %}
                                        <option value="{{item.id}}" data-chained="{{item.categoria.id}}">{{item.descripcion}}</option>
                                        {% endfor%}
                                    </select>
                                </div>
                            </div>                           
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="col-md-2">
                                    {{form.foto.label}}
                                </div>
                                <div class="col-md-8">
                                    {% if obj.foto %}
                                    <img src="{{obj.foto.url}}" width="100%" alt="">
                                    {% endif %}
                                </div>
                                <!-- <div class="col-md-4">{{form.foto}}</div> -->
                                <div class="col-md-2">
                                    <input type="file" name="foto" id="id_foto" accept="image/*">
                                </div>
                            </div>
                        </div>

                        <div class="dropdown-divider"></div>
                        <div class="row">
                            <div class="col">
                                <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span> Guardar</button>
                                <!-- <a href="{% url 'inv:um_list' %}" class="btn btn-success"><span class="fa fa-undo"></span>Cancelar</a> -->
                                <button type="button" class="btn btn-success" onclick="return cerrar_modal()">
                                    Cancelar
                                </button>
                            </div>
                        </div>
                    </div>
                    <div class="col-auto">
                        <i class="far fa-calendar-plus fa-2x text-gray-300"></i>
                    </div>
                    </div>
                </div>
                </div>
            </div>
        </form>
    </div>
</div>

<script>
    $(function() {
        $("#id_categoria").val("{{ obj.subcategoria.categoria.id }}").change();
        $("#id_subcategoria").val("{{ obj.subcategoria.id }}").change();
        $("#id_subcategoria").chained("#id_categoria");
    });
</script>

inv/templates/inv/subcategoria_list.html
{% extends 'base/base.html' %}

{% block page_content %}
<div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
      <h6 class="m-0 font-weight-bold text-primary">Listado de Categorías</h6>
      <div class="dropdown no-arrow">
        <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
          <div class="dropdown-header">Acciones</div>
          <a class="dropdown-item" href="{% url 'inv:subcategoria_new' %}"><i class="far fa-calendar-plus"></i> Nueva</a>  
        </div>

      </div>
    </div>

    <!-- Card Body -->
    <div class="card-body">
      {% if not obj %}
      <div class="alert alert-info">No hay Sub categorías</div>
      {% else %}
      <table class="table table-striped table-hover">
          <thead>
              <th>Categoria</th>
              <th>Id</th>
              <th>Descripción</th>
              <th>Estado</th>
              <th>F. Creado</th>
              <th>F. Modif.</th>
              <th class="all">Acciones</th>
          </thead>
          <tbody>
              {% for item in obj %}
              <tr>
                  <td>{{ item.categoria}}</td>
                  <td>{{ item.id }}</td>
                  <td>{{ item.descripcion }}</td>
                  <td>{{ item.estado|yesno:"Activo,Inactivo" }}</td>
                  <td>{{ item.fc|date:"d/m/Y H:i:s" }}</td>
                  <td>{{ item.fm|date:"d/m/Y H:i:s" }}</td>
                  <td>
                    <a href="{% url 'inv:subcategoria_edit' item.id %}" class="btn btn-warning btn-circle" role="button"><i class="far fa-edit"></i></a> 
                    <a href="{% url 'inv:subcategoria_del' item.id %}" class="btn btn-danger btn-circle" role="button"><i class="far fa-trash-alt"></i></a>
                  </td>
              </tr>
              {% endfor %}
          </tbody>
      </table>
      {% endif %}
    </div>
  </div>

{% endblock %}

{% block js_page %}
<script>
  // Call the dataTables jQuery plugin
  $(document).ready(function() {
    $('.table').DataTable();
  });
</script>
{% endblock %}

inv/templates/inv/um_form.html
{% extends 'base/base.html' %}
{% block page_content %}
<form method="POST" class="form-inline">
    <div class="col-xl-12 col-md-12 mb-12">
        {% if obj %}
        <div class="card border-left-warning shadow h-100 py-2">
        {% else %}
        <div class="card border-left-success shadow h-100 py-2">
        {% endif %}
        <div class="card-body">
            <div class="row no-gutters align-items-center">
            <div class="col mr-2">
                <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                    {% if obj %} Editar {% else %} Nueva {% endif %} Unidad de Medida
                </div>
                <div class="dropdown-divider"></div>
                {% csrf_token %}
                <div class="row">
                    <div class="col-10">
                        <div class="input-group">
                            {{ form.descripcion }}
                        </div>
                    </div>
                    <div class="col-2">
                        <div class="input-group">
                            <label for="id_estado">Estado</label>
                            <!-- <input type="checkbox" name="estado" class="form-control" id="id_estado" {% if obj.estado %} checked {% endif %} > -->
                            {{ form.estado }}
                        </div>
                    </div>        
                    <!-- {{ form.as_p }} -->
                </div>
                <div class="dropdown-divider"></div>
                <div class="row">
                    <div class="col">
                        <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span> Guardar</button>
                        <a href="{% url 'inv:um_list' %}" class="btn btn-success"><span class="fa fa-undo"></span>Cancelar</a>
                    </div>
                </div>
            </div>
            <div class="col-auto">
                <i class="far fa-calendar-plus fa-2x text-gray-300"></i>
            </div>
            </div>
        </div>
        </div>
    </div>
</form>
{% endblock %}